version: "3"
services:
  eureka:
    build:
      context: .
      dockerfile: localizador-servico/Dockerfile.compose
    image: eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-network
  db-produto:
    image: mysql:5.7
    networks:
      - produto-db-network
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=gerenciador
      - MYSQL_PASSWORD=produto
      - MYSQL_USER=gerenciador
      - MYSQL_DATABASE=gerenciar-produto
  gerenciar-produto:
    build:
      context: .
      dockerfile: gerenciar-produto/Dockerfile.compose
    image: produto
    environment:
      - DB_HOST=db-produto
      - DB_PORT=3308
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - db-produto
      - eureka
    networks:
      - produto-db-network
      - conta-db-network
      - pessoa-db-network
      - eureka-network
    ports:
      - "8083:8083"
  db-conta:
    image: mysql:5.7
    networks:
      - conta-db-network
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=gerenciador
      - MYSQL_PASSWORD=conta
      - MYSQL_USER=gerenciador
      - MYSQL_DATABASE=gerenciar-conta
  gerenciar-conta:
    build:
      context: .
      dockerfile: gerenciar-conta/Dockerfile.compose
    image: conta
    environment:
      - DB_HOST=db-conta
      - DB_PORT=3307
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - db-conta
      - eureka
    networks:
      - produto-db-network
      - conta-db-network
      - pessoa-db-network
      - eureka-network
    ports:
      - "8082:8082"
  db-pessoa:
    image: mysql:5.7
    networks:
      - conta-db-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=gerenciador
      - MYSQL_PASSWORD=pessoa
      - MYSQL_USER=gerenciador
      - MYSQL_DATABASE=gerenciar-pessoa
  gerenciar-pessoa:
    build:
      context: .
      dockerfile: gerenciar-pessoa/Dockerfile.compose
    image: pessoa
    environment:
      - DB_HOST=db-pessoa
      - DB_PORT=3306
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - db-pessoa
      - eureka
    networks:
      - produto-db-network
      - conta-db-network
      - pessoa-db-network
      - eureka-network
    ports:
      - "8081:8081"

networks:
  produto-db-network:
  conta-db-network:
  pessoa-db-network:
  eureka-network:
