version: "3"
services:
  eureka:
    build:
      context: .
      dockerfile: localizador-servico/Dockerfile
    image: eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-network
  db-produto:
    image: mysql:5.7
    networks:
      - produto-db-network
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gerenciador
      - MYSQL_PASSWORD=produto
      - MYSQL_USER=gerenciador
      - MYSQL_DATABASE=gerenciar-produto
  gerenciar-produto:
    build:
      context: .
      dockerfile: gerenciar-produto/Dockerfile.produto.dev
    image: produto
    environment:
      - DB_HOST=db-produto
      - DB_PORT=3308
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - db-produto
      - eureka
    networks:
      - produto-db-network
      - eureka-network
    ports:
      - "8082:8082"

networks:
  produto-db-network:
  eureka-network:
