FROM java:openjdk-8u111-alpine
ARG JAR_FILE=gerenciar-conta/target/*.jar
RUN apk --no-cache add curl
RUN curl -OL https://raw.githubusercontent.com/mrako/wait-for/master/wait-for && chmod +x wait-for
CMD     ./wait-for -t 300 $EUREKA_HOST:$EUREKA_PORT -- \
        ./wait-for -t 300 $DB_HOST:$DB_PORT -- \
        echo "All dependencies ready. Starting application..." && \
        java ${JAVA_OPTS} -jar gerenciar-conta.jar
COPY ${JAR_FILE} gerenciar-conta.jar